apiVersion: v1
kind: ServiceAccount
metadata:
  name: diki-operator
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: diki-operator
    helm.sh/chart: diki-operator
    app.kubernetes.io/instance: {{ .Release.Name }}
automountServiceAccountToken: false
