# SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: diki-operator
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: diki-operator
    helm.sh/chart: diki-operator
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: diki-operator
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  - name: metrics
    port: 8080
    protocol: TCP
    targetPort: {{ required ".Values.config.server.metrics.port is required" .Values.config.server.metrics.port }}
