# SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
description: A Helm chart to deploy the diki-operator related resources
name: diki-operator
version: 0.1.0
